#!/usr/bin/env bash
# Check if all required parameters are provided

if [ "$#" -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables

file_path=$1
ip=$2
username="$3"
ssh_key_path="$4"

# Disabling strict host key checking
scp -o "StrictHostKeyChecking=no" -i "$ssh_key_path" "$file_path" "$username@$ip:~/"
exit 0

# Checking if the transfer is successful
if [ $? -eq 0 ]
then
	echo "File transfered successfuly"
else
	echo "File transfer failed"
fi
