#!/usr/bin/env bash
# Display a list of currently running processes with hierarchy.

# Use the ps command to list all processes in a user-oriented format
ps -e -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest
