#!/usr/bin/env bash
# This script demonstrates signal handling and creates a PID file

echo $$ > /var/run/myscript.pid

trap "echo 'I hate the kill command'" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm -f /var/run/myscript.pid; exit" SIGQUIT SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 1
done
