#!/usr/bin/env bash
# Loop through all files in the current directory

for file in *; do
    # Check if the file is not hidden and contains a dash
    if [[ ! $file =~ ^\..* && $file =~ .*-.* ]]; then
        # Extract the part after the first dash
        new_name=$(echo "$file" | cut -d '-' -f 2-)
        echo "$new_name"
    fi
done
