#!/usr/bin/env bash

file_name="school"

if [ -e "$file_name" ]; then
    echo "$file_name file exists"
    if [ -s "$file_name" ]; then
        echo "$file_name is not empty"
        if [ -f "$file_name" ]; then
            echo "$file_name is a regular file"
        fi
    else
        echo "$file_name is empty"
    fi
else
    echo "$file_name file does not exist"
fi
